# Quarkus
quarkus.http.root-path=/api/cortex-m/v1
# Scheduler
quarkus.scheduler.start-mode=forced
# LangChain4j Config - Works for other providers to!
quarkus.langchain4j.openai.base-url=${PROVIDER_BASE_URL:http://localhost:11434/v1/}
quarkus.langchain4j.openai.chat-model.model-name=${PROVIDER_CHAT_MODEL_NAME:qwen3:14b}
quarkus.langchain4j.openai.api-key=${PROVIDER_API_KEY:dummy}
quarkus.langchain4j.openai.timeout=${PROVIDER_TIMEOUT:180s}
quarkus.langchain4j.openai.chat-model.temperature=${PROVIDER_CHAT_MODEL_TEMPERATURE:0.7}
%dev.quarkus.langchain4j.log-requests=true
# Embeddings
quarkus.langchain4j.openai.embedding-model.model-name=${PROVIDER_EMEDDNING_MODEL_NAME:snowflake-arctic-embed:latest}
quarkus.langchain4j.pgvector.dimension=1024